# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageSearch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImageSearch
  pod "lottie-ios"


  target 'ImageSearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ImageSearchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
